### ISSUE TITLE
Canal j

### ISSUE THREAD

**Issue by dalmore72** [Jasmeet181/mediaportal-be-logos#1]
Canal j new logo

https://icicestbranding.fr/rebrand/canal-j-change-didentite/

![canalj](https://user-images.githubusercontent.com/16014375/63716055-67b93380-c845-11e9-89aa-b794094874a5.png)

**Comment by Jasmeet181** [comment]
Thank you Dalmore.

**Comment by dalmore72** [comment]
Thanks 👍
