### ISSUE TITLE
New logos

### ISSUE THREAD

**Issue by dalmore72** [Jasmeet181/mediaportal-be-logos#2]
New logo Histoire Tv and Ushuaia Tv

[New.zip](https://github.com/Jasmeet181/mediaportal-be-logos/files/3983185/New.zip)

**Comment by Jasmeet181** [comment]
Thanks Dalmore, the TV Breizh logo has also changed a little (added a dot above the i, removed the gradient), the SVGs for all three are here
https://tf1-et-vous.tf1.fr/votre-tele/vos-chaines

**Comment by dalmore72** [comment]
Thanks
